# Generated by Django 2.2.5 on 2020-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='d_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
