# Generated by Django 2.2.5 on 2020-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_d_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='aaaaa'),
            preserve_default=False,
        ),
    ]
