# Generated by Django 2.2.5 on 2020-07-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='d_price',
            new_name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='descreption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
